# Generated by Django 6.0.5 on 2026-06-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("D", "DONE"), ("P", "IN_PROGRESS"), ("B", "BACKLOG")],
                default="P",
                max_length=2,
            ),
        ),
    ]
