# Generated by Django 6.0.5 on 2026-06-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("L", "Low"),
                    ("M", "Medium"),
                    ("H", "High"),
                    ("C", "Critical"),
                ],
                default="M",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("B", "Backlog"), ("P", "In Progress"), ("D", "Done")],
                default="P",
                max_length=2,
            ),
        ),
    ]
